package org.SchoolApp.Web.Dtos.Response;

import lombok.Data;

@Data
public class ApprenantResponseDto {
    private Long id;
    private String nomTuteur;
    private String prenomTuteur;
    private String contactTuteur;
    private String matricule;    // Generated matricule for the student
    private String qrCodeLink;   // QR code generated by external service

    private UserResponseDto user;    // Associated user account details
    private String referentiel;      // Referentiel name or relevant data
    private String promo;            // Promo name or relevant data
}
